'''
    â†’ Try, Except

    â†’ Exception handling

    â†’ Built-in Exceptions:
        https://docs.python.org/3/library/exceptions.html
'''

# ðŸ’¡ declare (any error)
try:
    print(a)
except:
    print('Error')

# ðŸ’¡ NameError, Exception
try:
    print(a)
except NameError as error:
    print('Error:', error)
except Exception as error:
    print('Unexpected Error:', error)

# ðŸ’¡ Multiple errors
try:
    a = []
    a[1]
except (IndexError, KeyError) as error:
    print('Index or Key error:', error)
    
# ðŸ’¡ else - In case where there is no error will be executed
# ðŸ’¡ finally - Will always run
try:
    print('Success!')
except:
    print('Error')
else:
    print('Success!')
finally:
    print('Success!')

'''
    â†’ Throwing your next exceptions
'''

# ðŸ’¡ raise
def division(n1, n2):
    if n2 == 0:
        raise ValueError('n2 cannot be zero')
    return n1 / n2
    
# ðŸ’¡ catch exception  
try:
    division(10, 0)
except ValueError as error:
    print(error)
    
# ðŸ’¡ 
# ðŸ’¡ 
# ðŸ’¡ 
# ðŸ’¡ 